[database]
    name     = "vulcanize_public"
    hostname = "localhost"
    port     = 5432
    user     = "vdbm"
    password = "password"

[client]
    rpcPath  = "http://eth-server:8081"

[graphql]
    uri = "http://localhost:5000"

[contract]
    network  = ""
    addresses  = [
        "0x2524411ca3fb997352825a705b47a2d5b9cbcfa4",
    ]
    [contract.0x2524411ca3fb997352825a705b47a2d5b9cbcfa4]
        abi    = '[{"inputs":[{"internalType":"uint256","name":"y","type":"uint256"}],"stateMutability":"nonpayable","type":"constructor"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"buyer","type":"address"}],"name":"onSold","type":"event"},{"inputs":[],"name":"off","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"on","outputs":[],"stateMutability":"nonpayable","type":"function"}]'
        events = [
            "onSold",
        ]
        storageKeys = [
            "0x0000000000000000000000000000000"
        ]
        methods = [
            "message"
        ]
        startingBlock = 1

[ethereum]
    nodeID = "arch1" # $ETH_NODE_ID
    clientName = "Geth" # $ETH_CLIENT_NAME
    genesisBlock = "0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3" # $ETH_GENESIS_BLOCK
    networkID = "4" # $ETH_NETWORK_ID
    chainID = "4" # $ETH_CHAIN_ID

#[log]
#    level = "debug"