[database]
    name     = "vulcanize_public"
    hostname = "contact-watcher-db"
    port     = 5432
    user     = "vdbm"
    password = "password"

[client]
    rpcPath  = "http://eth-server:8081"

[ethereum]
    nodeID = "arch1" # $ETH_NODE_ID
    clientName = "Geth" # $ETH_CLIENT_NAME
    genesisBlock = "0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3" # $ETH_GENESIS_BLOCK
    networkID = "4" # $ETH_NETWORK_ID
    chainID = "4" # $ETH_CHAIN_ID