version: '3.2'

services:
  geth:
    image: ethereum/client-go:v1.9.11
    expose:
    - "8545"
    - "8546"
    ports:
    - "127.0.0.1:8545:8545"
    - "127.0.0.1:8546:8546"
    command: ["--syncmode", "full",
              "--cache", "4096",
              "--cache.database", "50",
              "--cache.gc", "50",
              "--rpc",
              "--rpcapi", "eth,net"]

  contact-watcher-db:
    restart: always
    image: postgres:10.12-alpine
    environment:
      - POSTGRES_USER=vdbm
      - POSTGRES_DB=vulcanize_public
      - POSTGRES_PASSWORD=password
    volumes:
    - vulcanizedb_db_data:/var/lib/postgresql/data
    expose:
    - "5432"
    ports:
    - "127.0.0.1:8079:5432"

  eth-header-sync:
    depends_on:
    - contact-watcher-db
    build:
      context: ./../
      cache_from:
      - alpine:latest
      - golang:1.13
      dockerfile: ./dockerfiles/header_sync/Dockerfile
      args:
        USER: "vdm"
        CONFIG_FILE: ./environments/example.toml
    volumes:
      - ./geth.ipc:/geth.ipc
    environment:
      - STARTING_BLOCK_NUMBER=3327410
      - VDB_COMMAND=sync
      - DATABASE_NAME=vulcanize_public
      - DATABASE_HOSTNAME=contact-watcher-db
      - DATABASE_PORT=5432
      - DATABASE_USER=vdbm
      - DATABASE_PASSWORD=password

  eth-contract-watcher:
    depends_on:
    - contact-watcher-db
    build:
      context: ./../
      cache_from:
      - alpine:latest
      - golang:1.13
      dockerfile: ./dockerfiles/Dockerfile
    volumes:
     - ./geth.ipc:/geth.ipc
    environment:
      - VDB_COMMAND=watch
      - DATABASE_NAME=vulcanize_public
      - DATABASE_HOSTNAME=contact-watcher-db
      - DATABASE_PORT=5432
      - DATABASE_USER=vdbm
      - DATABASE_PASSWORD=password

  contract-watcher-graphql:
    restart: always
    depends_on:
    - contact-watcher-db
    image: vulcanizejenkins/postgraphile:v1.0
    environment:
      - PG_HOST=contact-watcher-db
      - PG_PORT=5432
      - PG_DATABASE=vulcanize_public
      - PG_USER=vdbm
      - PG_PASSWORD=password
      - SCHEMA=public,eth
    ports:
    - "127.0.0.1:5000:5000"

volumes:
  vulcanizedb_db_data: